CREATE COLUMN TABLE "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST" ("INSERT_TS" NVARCHAR(21), "JOB_CODE" NVARCHAR(6), "ESI_ID" NVARCHAR(22), "ACCT_NO" NVARCHAR(12), "METER_NO" NVARCHAR(9), "ONSITE_DT" NVARCHAR(10), "ONSITE_TIME" NVARCHAR(8), "COMPLETION_DT" NVARCHAR(10), "COMPLETION_TIME" NVARCHAR(8), "CAPTURE_DT" NVARCHAR(23), "ADDRESS" NVARCHAR(80), "AMS_INDICATOR" NVARCHAR(1), "TECH_ID" NVARCHAR(8), "TRUCK_NO" NVARCHAR(5), "METER_CATEGORY" NVARCHAR(4), "SERVICE_CENTER" NVARCHAR(13)) UNLOAD PRIORITY 5  AUTO MERGE ;
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."INSERT_TS" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."JOB_CODE" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."ESI_ID" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."ACCT_NO" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."METER_NO" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."ONSITE_DT" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."ONSITE_TIME" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."COMPLETION_DT" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."COMPLETION_TIME" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."CAPTURE_DT" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."ADDRESS" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."AMS_INDICATOR" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."TECH_ID" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."TRUCK_NO" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."METER_CATEGORY" is ' ';
COMMENT ON COLUMN "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"."SERVICE_CENTER" is ' '